<a href="https://colab.research.google.com/github/Himanshi143/Machine-Learning-By-Campusx/blob/main/Day-45/feature_construction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [4]:
df=pd.read_csv('/content/train.csv',usecols=[1,2,5,6,7])
df.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [5]:
df.dropna(inplace=True)

In [8]:
x=df.iloc[:,1:]
y=df.iloc[:,0]

In [9]:
x

     Pclass   Age  SibSp  Parch
0         3  22.0      1      0
1         1  38.0      1      0
2         3  26.0      0      0
3         1  35.0      1      0
4         3  35.0      0      0
..      ...   ...    ...    ...
885       3  39.0      0      5
886       2  27.0      0      0
887       1  19.0      0      0
889       1  26.0      0      0
890       3  32.0      0      0

[714 rows x 4 columns]

In [10]:
y

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: Survived, Length: 714, dtype: int64

In [14]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20))

0.6933333333333332

In [15]:
df['family_size']=df['Parch']+df['SibSp']

In [16]:
df.head()

   Survived  Pclass   Age  SibSp  Parch  family_size
0         0       3  22.0      1      0            1
1         1       1  38.0      1      0            1
2         1       3  26.0      0      0            0
3         1       1  35.0      1      0            1
4         0       3  35.0      0      0            0

In [17]:
def fam(num):
  if(num==0):
    return 0
  elif(num>0 and num<=4):
    return 1
  else:
    return 2

In [18]:
df['fam_type']=df['family_size'].apply(fam)

In [19]:
df.head()

   Survived  Pclass   Age  SibSp  Parch  family_size  fam_type
0         0       3  22.0      1      0            1         1
1         1       1  38.0      1      0            1         1
2         1       3  26.0      0      0            0         0
3         1       1  35.0      1      0            1         1
4         0       3  35.0      0      0            0         0

In [20]:
df.drop(columns=['SibSp','Parch','family_size'],inplace=True)

In [21]:
df.head()

   Survived  Pclass   Age  fam_type
0         0       3  22.0         1
1         1       1  38.0         1
2         1       3  26.0         0
3         1       1  35.0         1
4         0       3  35.0         0

In [25]:
x_=df.iloc[:,1:]
y_=df.iloc[:,0]

In [26]:
np.mean(cross_val_score(LogisticRegression(),x_,y_,scoring='accuracy',cv=20))

0.7031746031746031

Feature Splitting

In [27]:
df1=pd.read_csv('/content/train.csv')
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [31]:
df1['title']=df1['Name'].str.split(',',expand=True)[1].str.split('.',expand=True)[0]
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr

In [33]:
df1['title'].value_counts().sort_values(ascending=False)

title
 Mr              517
 Miss            182
 Mrs             125
 Master           40
 Dr                7
 Rev               6
 Major             2
 Col               2
 Mlle              2
 the Countess      1
 Capt              1
 Ms                1
 Sir               1
 Lady              1
 Mme               1
 Don               1
 Jonkheer          1
Name: count, dtype: int64

In [45]:
df1['is_married']=0
df1['is_married'].loc[df1['title']=='Mrs']=1

<ipython-input-45-57f0b84b8556>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['is_married'].loc[df1['title']=='Mrs']=1

In [43]:
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,title,is_married
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr,0